config/routes.rb
ReviseController::Application.routes.draw do
  
  resources :pages

  resources :users

  resources :products do
    resources :comments
  end

  root :to => 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  # include ActiveModel::Validations
  # include ActiveModel::Conversion
  # extend ActiveModel::Naming
  has_many :comments

  attr_accessible :name, :price

  validates_presence_of :name

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json


  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @comments = @product.comments
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :edit , notice: 'Product not successfully created.'
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(params[:product])
     redirect_to @product,notice: 'Product was successfully created.'
    else
      render :edit ,notice: 'Product not successfully created.'
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to products_path
      flash[:notice] = 'Product was successfully destroyed.'
    else
      redirect_to :back
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<p>
  <%= product.name %>
  <%= product.price %>
  <%= link_to 'Show', product %>
  <%= link_to 'Edit', edit_product_path(product.id) %>
</p>

<br >

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<%= render @products %>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p><strong>Comments:</strong></p>

<table>
  <% @comments.each do |comment| %>
    <tr>
      <td><p> - <%= comment.message %></p></td>
      <td><%= link_to "Edit", edit_product_comment_path(@product, comment) %></td>
      <td></td>
      <td></td>
    </tr>
  <% end %>
</table>

<table>
  <tr>
    <td><%= link_to 'Edit', edit_product_path(@product) %></td>
    <td><%= button_to 'Destroy', @product, method: :delete , data: {confirm: 'Are you sure?'} %></td>
    <td><%= link_to 'Back', products_path%></td>
  </tr>
</table>

<p>
  <%= link_to 'New Comment', new_product_comment_path(@product) %>
</p>